# SwiftLint configuration aligned with Apple Swift-NIO style
# Reference: https://github.com/apple/swift-nio

swiftlint_version: 0.59.1

# Match Swift-NIO's pragmatic approach
disabled_rules:
  # Swift-NIO allows these
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - identifier_name  # Allow underscores and short names when needed
  - trailing_newline  # Handled by SwiftFormat
  - file_length
  - function_body_length
  - type_body_length
  - line_length  # Handled by SwiftFormat (120 chars)
  - cyclomatic_complexity
  - function_parameter_count
  - large_tuple
  - todo  # Allow TODO comments
  - fixme  # Allow FIXME comments
  - trailing_whitespace  # Handled by SwiftFormat
  - vertical_whitespace  # Handled by SwiftFormat
  - trailing_comma  # Handled by SwiftFormat
  - opening_brace  # Handled by SwiftFormat
  - statement_position  # Handled by SwiftFormat
  - colon  # Handled by SwiftFormat
  - comma  # Handled by SwiftFormat

opt_in_rules:
  # Swift-NIO style rules
  - attributes
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

included:
  - Sources
  - Tests
  - Examples

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - .swiftpm
  - Package.swift
  - atest

# Swift-NIO compatible settings
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true

type_name:
  min_length: 1
  max_length: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true

identifier_name:
  min_length: 1
  max_length: 60
  allowed_symbols: ["_"]
  validates_start_with_lowercase: true
  excluded:
    - i
    - j
    - k
    - x
    - y
    - z
    - id
    - ID
    - URL
    - url

nesting:
  type_level:
    warning: 3
    error: 6
  function_level:
    warning: 5
    error: 10

file_header:
  required_pattern: |
    \/\/ .*\.swift - .*
    \/\/ Copyright © \d{4} SwinjectUtilityMacros\. All rights reserved\.

# Analyzer rules for better code quality
analyzer_rules:
  - capture_variable
  - explicit_self
  - unused_declaration
  - unused_import

# Custom rules matching Swift-NIO style
custom_rules:
  no_print:
    name: "Avoid print statements"
    regex: '\bprint\s*\('
    message: "Use os.log or Logger instead of print()"
    severity: warning
    excluded:
      - "Tests"
      - "Examples"

  no_nslog:
    name: "Avoid NSLog"
    regex: '\bNSLog\s*\('
    message: "Use os.log or Logger instead of NSLog()"
    severity: error

  empty_method:
    name: "Empty Method"
    regex: 'func\s+\w+\s*\([^)]*\)\s*(?:throws\s*)?(?:->\s*[^{]+)?\s*\{\s*\}'
    message: "Don't keep empty methods in code."
    severity: warning

  multiple_empty_lines:
    name: "Multiple Empty Lines"
    regex: '\n\n\n+'
    message: "There are too many line breaks (max 1 blank line)"
    severity: error

  vertical_whitespaces_around_mark:
    name: "Vertical Whitespaces Around MARK"
    regex: '\/\/\s*MARK:[^\n]*(\n\n)|(\n\n\n)[ \t]*\/\/\s*MARK:|[^\s{]\n[^\n\/]*\/\/\s*MARK:'
    message: "Include a single vertical whitespace (empty line) before and none after MARK: comments."
    severity: warning

  missing_docs:
    name: "Missing Docs"
    regex: '^\s*(?:public|open)\s+(?:class|struct|enum|protocol|func|var|let)'
    message: "public declarations should be documented"
    severity: warning
    match_kinds:
      - comment
      - doccomment
    excluded:
      - "Tests"

  numbers_smell:
    regex: '(return |case |\w\(|: |\?\? |\, |== |<=? |>=? |\+= |\-= |\/= |\*= |%= |\w\.\w+ = )\(*-?\d{2,}'
    message: "Numbers smell; define a constant instead."
    severity: warning
    excluded:
      - "Tests"

reporter: "xcode"
